#! /bin/sh
# Carry out specific functions when asked to by the system

case "$1" in
	start)
		start-stop-daemon --quiet --start --background --chuid root:root --exec /usr/sbin/gs-server/gs-server
		;;
	stop)
		start-stop-daemon --quiet --stop --exec /usr/sbin/gs-server
		;;
	*)
		echo "Usage: /etc/init.d/gsserver {start|stop}"
		exit 1
		;;
esac

exit 0
