#! /bin/sh
### BEGIN INIT INFO
# Provides:          await-docker-started
# Required-Start:     docker
# Required-Stop:
# Default-Start:
# Default-Stop:      2 3 4 5
# Short-Description: Waits until docker has been started.
# Description: 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

JOB=docker
TIMEOUT=330

do_wait () {
        log_action_begin_msg "Waiting for $JOB to be started"
        start_time=`date "+%s"`
        until status $JOB | grep start/running >/dev/null; do
                if [ $((`date "+%s"` - $start_time)) -gt $TIMEOUT ]; then 
                        log_action_end_msg 1
                        exit 0
                fi
                sleep 1
        done
        log_action_end_msg 0
}

case "$1" in
  start)
        do_wait
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

: