#!/bin/bash


function update_ent {
	tail -n1 /etc/passwd >> /var/lib/extrausers/passwd
	tail -n1 /etc/shadow >> /var/lib/extrausers/shadow
	tail -n1 /etc/group >> /var/lib/extrausers/group
}

case $1 in
	add)
		# if user not exist
		if ! id -u $2 >/dev/null 2>&1; then
			useradd -M -g nas $2
		fi
		echo "$2:$3" | chpasswd
		echo -e "$3\n$3" | (smbpasswd -a -s $2)
		update_ent
		;;
	delete)
		cp /etc/passwd /etc/shadow /etc/group /tmp/

		for file in passwd shadow group; do
			cat /var/lib/extrausers/$file >> /etc/$file
		done

		userdel $2

		for file in passwd shadow group; do
			diff /tmp/$file /etc/$file | sed -n '/^-[^-]/{ s/^-//; p; }' >> /var/lib/extrausers/$file
		done
		;;
	password)
		echo "$2:$3" | chpasswd
		echo -e "$3\n$3" | (smbpasswd -a -s $2)
		update_ent
		;;
	update)
		
		;;
	*)
		echo "Usage: nas-user"
		echo
		echo "	nas-user [add|delete|password] <user> <password>"
		echo
		echo "	*The password option is mandatory for 'add' and 'password'."
		;;
esac
