#!/bin/sh

### BEGIN INIT INFO
# Provides:          samba
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start Samba daemons (nmbd and smbd)
### END INIT INFO

# Reads config file
[ -r /etc/default/samba4 ] && . /etc/default/samba4

LOGDIR=/var/log/samba
PIDDIR=/opt/samba4/var/run
NMBDPID=$PIDDIR/nmbd.pid
SMBDPID=$PIDDIR/smbd.pid

# clear conflicting settings from the environment
unset TMPDIR

# See if the daemons are there
test -x /opt/samba4/sbin/nmbd -a -x /opt/samba4/sbin/smbd -a -r /etc/samba/smb.conf || exit 0


. /lib/lsb/init-functions

case "$1" in
        start)
                log_daemon_msg "Starting Samba 4 daemons"
                # Make sure we have our PIDDIR, even if it's on a tmpfs
                install -o root -g root -m 755 -d $PIDDIR
                # Make sure we have our LOGDIR, even if it's on a tmpfs
                install -o root -g root -m 755 -d $LOGDIR

                # Remove smbd-fileserver.conf.pid before starting up samba
                # needed for s3fs
                if [ -e $PIDDIR/smbd.pid ] ; then
                        rm -f $PIDDIR/smbd.pid
                fi

                NMBD_DISABLED=`testparm -s --parameter-name='disable netbios' 2>/dev/null`
                if [ "$NMBD_DISABLED" != 'Yes' ]; then
                        log_progress_msg "nmbd"
                        if ! start-stop-daemon --start --quiet --oknodo --exec /opt/samba4/sbin/nmbd -- -D
                        then
                                log_end_msg 1
                                exit 1
                        fi
                fi

                if ! start-stop-daemon --start --quiet --oknodo --exec /opt/samba4/sbin/samba -- -D; then
                        log_end_msg 1
                        exit 1
                fi

                log_end_msg 0
                ;;
        stop)
                log_daemon_msg "Stopping Samba 4 daemons"
                log_progress_msg "nmbd"

                start-stop-daemon --stop --quiet --pidfile $NMBDPID
                # Wait a little and remove stale PID file
                sleep 1
                if [ -f $NMBDPID ] && ! ps h `cat $NMBDPID` > /dev/null
                then
                        # Stale PID file (nmbd was succesfully stopped),
                        # remove it (should be removed by nmbd itself IMHO.)
                        rm -f $NMBDPID
                fi 

                log_progress_msg "smbd"
                start-stop-daemon --stop --quiet --pidfile $SMBDPID
                # Wait a little and remove stale PID file
                sleep 1
                if [ -f $SMBDPID ] && ! ps h `cat $SMBDPID` > /dev/null
                then
                        # Stale PID file (nmbd was succesfully stopped),
                        # remove it (should be removed by smbd itself IMHO.)
                        rm -f $SMBDPID
                fi

                log_end_msg 0
                ;;
        restart|force-reload)
                $0 stop
                sleep 1
                $0 start
                ;;
        *)
                echo "Usage: /etc/init.d/samba4 {start|stop|restart|force-reload}"
                exit 1
                ;;
esac

exit 0