#! /bin/sh
### BEGIN INIT INFO
# Provides:          await-docker-stopped
# Required-Start:    
# Required-Stop:     sendsigs
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Waits until docker has been stopped.
# Description: 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

JOB=docker
TIMEOUT=330

do_wait () {
        log_action_begin_msg "Waiting for $JOB to be stopped"
        start_time=`date "+%s"`
        until status $JOB | grep stop/waiting >/dev/null; do
                if [ $((`date "+%s"` - $start_time)) -gt $TIMEOUT ]; then 
                        log_action_end_msg 1
                        exit 0
                fi
                sleep 1
        done
        log_action_end_msg 0
}

case "$1" in
  start)
        # No-op
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        do_wait
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

: